version: "2"
services:
  server:
    build: 
      context: ./contacts-backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  web:
    build: 
      context: ./contacts-frontend
      dockerfile: Dockerfile
    depends_on: 
      - "server"
    ports:
      - "3001:3000"